language: node_js
node_js: node
sudo: false
cache: false

stages:
  - name: "application test & build"

jobs:
  include:
    - stage: "application test & build"
      name: "Team Chat Reference Application"
      install:
        - npm install
      script:
        - npm run test
        - npm run build
